export const TYPE_CHANGE = 'TYPE_CHANGE'
export const PLAIN_CHANGE = 'PLAIN_CHANGE'
export const FLY_CHANGE = 'FLY_CHANGE'
export const MAX_CHANGE = 'MAX_CHANGE'
export const INPUT_CHANGE = 'INPUT_CHANGE'
export const REF_CHANGE = 'REF_CHANGE'
export const REF_SIN_CHANGE = 'REF_SIN_CHANGE'
export const CANNON_CHANGE = 'CANNON_CHANGE'