export const listType = ['刀', '槍', '槌', '拳', '盾', '弓', '石弓', '鉄砲', '大砲', '法術', '杖', '歌舞', '鈴']
export const listTypeS = ['sword', 'lance', 'hammer', 'fist', 'shield', 'bow', 'xbow', 'arqu', 'cannon', 'spell', 'staff', 'dance', 'bell']

export const listBut = ['無巨大化', '巨大化一階', '巨大化二階', '巨大化三階', '巨大化四階', '巨大化五階']
export const listButS = ['max0', 'max1', 'max2', 'max3', 'max4', 'max5']

export const listRef = ['無精煉', '全精煉+10', '★4+10', '★3+10', '★2+10', '★1+10']
export const listRefS = ['ref0', 'refAll', 'ref4', 'ref3', 'ref2', 'ref1']

export const tableHead = ['', '★', '名稱', '精煉', '攻擊', '傷害', 'DPS', '攻擊(f)', '延遲(f)', '特殊效果']
export const tableInd = ['', 'rare', 'name', 'refText', 'atk', 'damage', 'dps', 'frame1', 'frame2', 'text']

export const tableCharHead = ['', '名稱', '武器種', '★', '屬性', '耐久係數', '攻擊係數', '防禦係數', '係數合計']
export const tableCharInd = ['', 'name', 'weapon', 'rarity', 'plain', 'hpF', 'atF', 'dfF', 'totF']

export const listMelee = ['sword', 'lance', 'hammer', 'fist', 'shield']
export const listMagic = ['spell', 'staff', 'dance', 'bell']
export const listPhys = ['sword', 'lance', 'hammer', 'fist', 'shield', 'bow', 'xbow', 'arqu', 'cannon']

export const listPlain = ['平', '平山', '山', '水']
export const listPlainS = [1, 2, 4, 8]
const listPlainQ1 = ['平']
const listPlainQ2 = ['平山']
const listPlainQ3 = ['平', '平山']
const listPlainQ4 = ['山']
const listPlainQ5 = ['平', '山']
const listPlainQ6 = ['平山', '山']
const listPlainQ7 = ['平', '平山', '山']
const listPlainQ8 = ['水']
const listPlainQ9 = ['平', '平水']
const listPlainQ10 = ['平山', '平山水']
const listPlainQ11 = ['平', '平山', '平水', '平山水']
const listPlainQ12 = ['山', '山水']
const listPlainQ13 = ['平', '山', '平水', '山水']
const listPlainQ14 = ['平山', '山', '平山水', '山水']
const listPlainQ15 = ['平', '平山', '山', '平水', '平山水', '山水']
export const listPlainQ = [listPlainQ1, listPlainQ2, listPlainQ3, listPlainQ4, listPlainQ5, listPlainQ6, listPlainQ7, listPlainQ8, listPlainQ9, listPlainQ10, listPlainQ11, listPlainQ12, listPlainQ13, listPlainQ14, listPlainQ15]
